version: "3.3"
services:

  plaso:
    image: log2timeline/plaso
    container_name: plaso
    volumes:
      - ./data/plaso:/data/

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: plaso-es
    volumes:
      - data01:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=es-dev
      - xpack.security.enabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - "es:elasticsearch"
    volumes:
      - ./settings/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es

  svr:
    image: cybagard/nsrllookup-svr:latest
    volumes:
      - ./data/nsrlsvr/:/usr/local/share/nsrlsvr/

  api:
    image: cybagard/nsrllookup-api:latest
    depends_on:
      - svr
    command: sh -c "/wait && python /api/app.py"
    environment:
      - WAIT_HOSTS=svr:9120
      - WAIT_HOSTS_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - SERVER=svr
    ports:
      - 5000:5000  

  dev:
    build: settings/dev
    volumes:
      - ~/stix/:/stix

volumes:
  data01:
