version: "3.3"
services:

  # plaso:
  #   profiles:
  #     - plaso
  #   image: log2timeline/plaso
  #   container_name: plaso
  #   volumes:
  #     - ./data/plaso:/data/

  dev:
    build: .
    volumes:
      - ./data/plest/:/data
    networks: 
      - plest
    environment:
      - STIX_ES_HOST=es:9200
      - STIX_ES_USERNAME=elastic
      - STIX_ES_PASSWORD=changeme
    command: python3 stix.py /stix/*.json

volumes:
  data01:

networks: 
  plest: