version: "3.3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: plaso-es
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - plaso
    environment:
      - node.name=es01
      - cluster.name=es-dev
      - xpack.security.enabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    netowrks:
      - plaso
    ports:
      - "5601:5601"
    links:
      - "es:elasticsearch"
    volumes:
      - ./settings/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es

volumes:
  data01:

networks: 
  plaso:  