version: "3.3"
services:
  dev:
    image: dev:latest
    volumes:
      - ./data/stix/:/stix
    environment:
      - STIX_ES_HOST=es:9200
      - STIX_ES_USERNAME=elastic
      - STIX_ES_PASSWORD=changeme
    command: /bin/bash -c python3 stix.py /stix/*.json
    networks:
      - plest_default
    
networks:
  plest_default:
    external: true